language: java
jdk:
  - oraclejdk8

sudo: false

script: "mvn cobertura:cobertura"

notifications:
  email:
    recipients:
      - fahreza.tamara@gmail.com
    on_success: always
    on_failure: always
