language: java
sudo: false

jdk:
- oraclejdk8

before_install:
  - chmod +x mvnw

before_script:
- openssl aes-256-cbc -K $encrypted_32c60f8c357d_key -iv $encrypted_32c60f8c357d_iv -in owl-dev.pem.enc -out owl-dev.pem -d

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: "mvn -B clean install"

after_success:
  - eval "$(ssh-agent -s)"
  # deploy to development server
  - chmod 600 owl-dev.pem
  - ssh-add owl-dev.pem
  - ssh-keygen -R $DEVELOPMENT_HOST
  - ssh-keyscan -H $DEVELOPMENT_HOST >> ~/.ssh/known_hosts
  - ssh -v -i develop.pem $DEVELOPMENT_SSH_USER@$DEVELOPMENT_HOST DEVELOPMENT_APP_PATH=$DEVELOPMENT_APP_PATH DEVELOPMENT_BRANCH=$DEVELOPMENT_BRANCH 'bash -s' < deploy-devel.sh

notifications:
  email:
    recipients:
      - fahreza.tamara@gmail.com
    on_success: always
    on_failure: always
